sonar.projectKey=anastaskanina1988-boop_qa-auto-engineer-python-project-314
sonar.organization=anastaskanina1988-boop
sonar.projectName=qa-auto-engineer-python-project-314
sonar.sources=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
